pool 2.debian.pool.ntp.org iburst
sourcedir /run/chrony-dhcp

refclock PPS /dev/pps0 refid PPS precision 1e-7 poll 2 prefer

sourcedir /etc/chrony/sources.d
keyfile /etc/chrony/chrony.keys
driftfile /var/lib/chrony/chrony.drift
ntsdumpdir /var/lib/chrony
logdir /var/log/chrony

maxupdateskew 100.0
rtcsync
makestep 1.0 -1
leapseclist /usr/share/zoneinfo/leap-seconds.list
confdir /etc/chrony/conf.d

allow 10.0.0.0/24
allow 192.168.8.0/24
